export default {
    'access bank plc': "../../../../assets/img/banks-img/access.png",
    'fidelity bank plc': "../../../../assets/img/banks-img/fidelity.png",
    'first city monument bank limited': "../../../../assets/img/banks-img/fcmb.png",
    'first bank of nigeria plc': "../../../../assets/img/banks-img/firstbank.png",
    'guaranty trust bank plc': "../../../../assets/img/banks-img/gtb.png",
    'union bank of nigeria plc': "../../../../assets/img/banks-img/union.png",
    'united bank for africa plc': "../../../../assets/img/banks-img/uba.png",
    'zenith bank plc': "../../../../assets/img/banks-img/zenith.png",
    'citibank nigeria limited': "../../../../assets/img/banks-img/citi.png",
    'ecobank nigeria plc': "../../../../assets/img/banks-img/ecobank.png",
    'heritage banking company limited': "../../../../assets/img/banks-img/heritage.png",
    'keystone bank limited': "../../../../assets/img/banks-img/keystone.png",
    'polaris bank plc': "../../../../assets/img/banks-img/polaris.png",
    'stanbic ibtc bank plc': "../../../../assets/img/banks-img/stanbic.png",
    'standard bank': "../../../../assets/img/banks-img/sb.png",
    'standard chartered': "../../../../assets/img/banks-img/standard.png",
    'standard chartered bank nigeria': "../../../../assets/img/banks-img/standard.png",
    'sterling bank plc': "../../../../assets/img/banks-img/sterling.png",
    'unity bank plc': "../../../../assets/img/banks-img/unity.png",
    'wema bank plc': "../../../../assets/img/banks-img/wema.png",
    'providus bank limited': "../../../../assets/img/banks-img/providus.png",
    'bank phb plc': "../../../../assets/img/banks-img/keystone.png",
    'standard bank of south africa': "../../../../assets/img/banks-img/sb.png",
    
}